### ISSUE TITLE
Inconsistent Transparency

### ISSUE THREAD

**Issue by fa7ad** [fa7ad/xgtk-kxmylo#3]
Appears in both light and dark mode
![screenshot from 2015-01-21 23 15 23](https://cloud.githubusercontent.com/assets/7447677/5840967/78c25b8c-a1c3-11e4-985f-79fe04340479.png)
![screenshot from 2015-01-21 23 14 54](https://cloud.githubusercontent.com/assets/7447677/5840976/85a3e988-a1c3-11e4-965a-425451ddcb8b.png)

**Comment by horst3180** [comment]
Hi, I think this is a bug in Gtk or Gnome Tweak tool and I don't think there's a fix for it.

**Comment by fa7ad** [comment]
okay then, this is not really an issue is it?
/closed
